# Generated by Django 5.2.1 on 2025-05-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categgory',
            new_name='category',
        ),
    ]
